FROM maksymc/node13-awscli:demo

# EXECUTE: docker build -t node-awscli:demo .
# EXECUTE: docker images | grep node-awscli

# EXECUTE: docker run --name node_awscli -it node-awscli:demo

# EXECUTE: docker stop node_awscli
# EXECUTE: docker rm node_awscli